name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

# If your app is in a subfolder, uncomment and set it:
# defaults:
#   run:
#     working-directory: client

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use cached setup only when a lockfile exists
      - name: Setup Node.js (with cache)
        if: ${{ hashFiles('**/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            **/npm-shrinkwrap.json

      # Fallback: setup without cache
      - name: Setup Node.js (no cache)
        if: ${{ hashFiles('**/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Prefer npm ci when a lockfile exists
      - name: Install dependencies (npm ci)
        if: ${{ hashFiles('**/package-lock.json') != '' }}
        run: npm ci

      - name: Install dependencies (npm install)
        if: ${{ hashFiles('**/package-lock.json') == '' }}
        run: npm install

      - name: Run tests
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present
